services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data # persist /data in which redis within the container stores data to the volume
    networks:
      - default

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2396
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docs/blog.sql:/docker-entrypoint-initdb.d/blog.sql # init `blog` with blog.sql
    networks:
      - default

  blog:
    build: ./blog
    image: endlessparadox1/blog
    container_name: blog
    volumes:
      - ./docs/config.toml:/root/server/config.toml 
    networks:
      - default
    logging:
      driver: "json-file"
    depends_on:
      - db
      - redis

  nginx:
    # build: ./nginx
    image: endlessparadox1/nginx
    container_name: nginx
    volumes:
      - /root/cert:/etc/nginx/cert # access SSL certificate
      - ./docs/nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - default
    ports:
      - "443:443"
    depends_on:
      - blog

volumes:
  redis_data:
  db_data:

networks:
  default:
    name: blog
